version: "3"
services:
  front:
    image: gitasap.ru:5050/it/gosti/front:0.1.8
    container_name: gosti-prod-front
    networks:
      - server
  back:
    image: gitasap.ru:5050/it/gosti/back:0.1.7
    container_name: gosti-prod-back
    volumes:
      - ./storage:/app/storage/app/public
    env_file:
      - .env
    networks:
      - server
  db:
    image: harbor.tomsk-it.ru/dockerhub/bitnami/postgresql:15.3.0-debian-11-r17
    container_name: gosti-prod-db
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}
    volumes:
      - ./postgresql_data:/bitnami/postgresql
    networks:
      - server
networks:
  server:
    external: true
